name: Deploy page
on:
  push:
    branches:
      - main2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: list files
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Setup cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }} # Aquí recuperas el valor
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
                ${{ runner.os }}-node-

      - name: Logs in summary
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY


      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
     