name: Summary
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: list files
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Logs in summary
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
     